### ISSUE TITLE
日本語のラベルが検索できない

### ISSUE THREAD

**Issue by soudai** [TakahashiIkki/previous-issue-finder#8]
# 問題点
`previous_issue` で指定するlabelは日本語に対応していない。

以下の書き方はどちらもヒットしないため、エラーになる。

```
        id: previous_issue
        with:
          label: 日報

        id: previous_issue
        with:
          label: "日報"
```

dailyの用に英語は検索できるので英語のlabelを作れば問題は回避はできる。

# ログ
```
##[debug]Evaluating condition for step: 'Get previous issue'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Get previous issue
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run TakahashiIkki/previous-issue-finder@v1.1.0
  with:
    label: daily
    repo_token: ***
  env:
    LC_ALL: ja_JP.UTF-[8](https://github.com/HaveFunTech/work/actions/runs/6732357636/job/18298903735#step:4:8)
    TZ: Asia/Tokyo
Error: 指定したタグでIssueが発見できませんでした.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Get previous issue
```

**Comment by TakahashiIkki** [comment]
やるぞー

**Comment by TakahashiIkki** [comment]
検索できるようになっている .. ? 

https://github.com/TakahashiIkki/previous-issue-finder/actions/runs/6837864320/job/18594406923

何か検索出来ないパターンがあるかデバッグする

**Comment by TakahashiIkki** [comment]
<img width="558" alt="image" src="https://github.com/TakahashiIkki/previous-issue-finder/assets/15377887/1713904b-0004-4c67-80ca-cdb2c67bb875">

Githubで検索する時は エスケープされてるので、取り敢えず escape するか〜.

https://github.com/search?q=repo%3ATakahashiIkki%2Fprevious-issue-finder%20label%3A%E6%97%A5%E5%A0%B1&type=issues

**Comment by TakahashiIkki** [comment]
@soudai 

issue記入ありがとうございます！！
v1.2.1 で対応したので、新しいの使ってみてもらえますか〜！
https://github.com/marketplace/actions/previous-issue-finder

**Comment by soudai** [comment]
なんと動いたのでOKです！
